const styles = {
  quizContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: "#eef2f3",
  },
  quizCard: {
    background: "#fff",
    borderRadius: "15px",
    padding: "30px",
    width: "900px",
    height: "600px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow: "0px 10px 20px rgba(0, 0, 0, 0.2)",
    textAlign: "center",
    position: "relative",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    fontSize: "18px",
    fontWeight: "bold",
    paddingBottom: "10px",
    borderBottom: "2px solid #ddd",
    position: "relative",
  },
  timer: {
    position: "absolute",
    right: "100px", 
    fontSize: "18px",
    fontWeight: "bold",
    color: "#dc3545",
    background: "#fff5f5",
    padding: "5px 10px",
    borderRadius: "5px",
    border: "2px solid #dc3545",
  },
  imageContainer: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    flexGrow: 1,
    marginTop: "20px",
  },
  image: {
    maxWidth: "90%",
    maxHeight: "250px",
    width: "50%",
    borderRadius: "10px",
    boxShadow: "0px 4px 8px rgba(0, 0, 0, 0.1)",
  },
  options: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "15px",
    width: "100%",
  },
  option: {
    background: "#fff",
    border: "3px solid black", 
    padding: "14px",
    fontSize: "18px",
    fontWeight: "bold", 
    cursor: "pointer",
    borderRadius: "8px",
    width: "100%",
    transition: "all 0.3s ease",
    boxShadow: "0px 4px 8px rgba(0, 0, 0, 0.1)",
  },
  
  correct: {
    borderColor: "#28a745",
    background: "#c8f7c5",
    transform: "scale(1.05)",
  },
  incorrect: {
    borderColor: "#dc3545",
    background: "#f8d7da",
    transform: "scale(1.05)",
  },
  nextButton: {
    padding: "14px 20px",
    background: "linear-gradient(90deg, #007bff, #0056b3)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "18px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.2)",
    marginTop: "40px",
  },
  result: {
    textAlign: "center",
    fontSize: "20px",
  },
  restartButton: {
    padding: "14px 20px",
    background: "linear-gradient(90deg, #dc3545, #a71d2a)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "18px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.2)",
    marginTop: "20px",
  },
  quizContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: "#eef2f3",
  },
  startButton: {
    padding: "20px 40px",
    fontSize: "20px",
    background: "linear-gradient(90deg, #28a745, #218838)",
    color: "white",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.2)",
  },
};

export default styles;
